load_from=${1:-none}  # --load_from name --resume
python -m torch.distributed.launch --nproc_per_node=2 --master_port=23456 \
                ez_run.py \
                --prefix opt \
                --mode test \
                --data_prefix "/private/home/jgu/data/" \
                --dataset "wmt16" \
                --src "ro" --trg "en" \
                --train_set "train.bpe.l2r" \
                --dev_set   "dev.bpe"  \
                --test_set "test.bpe" \
                --vocab_file "ro-en/vocab.ins.pt" \
                --load_lazy \
                --base "bpe" \
                --workspace_prefix "/private/home/jgu/space/Insertable/" \
                --eval_every 500  \
                --att_plot_every 2000 \
                --print_every 20 \
                --batch_size 2000 \
                --inter_size 2 \
                --label_smooth 0.1 \
                --share_embeddings \
                --tensorboard \
                --cross_attn_fashion "forward" \
                --load_from ${load_from} \
                --length_ratio 2 \
                --beam_size 10 \
                --alpha 1.0 \
                --relative_pos \
                --model TransformerIns \
                --insertable --insert_mode word_first \
                --debug \
                --decode_test
